# -*- coding: utf-8 -*-
"""discovery_engine.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MLWr5vIb7QedFKEGU2LZ341qA-W5chU6

### `discovery_engine.py`: Core Engine Structure

This file will contain the main logic for capturing network packets, detecting AI API calls, and managing the findings in a SQLite database.
"""

from scapy.all import sniff, IP, TCP, UDP, DNS, Raw, rdpcap
import sqlite3
import re
import datetime
import time
import threading

# Database setup
DB_NAME = 'discovery.db'

class DiscoveryEngine:
    def __init__(self):
        self.db_name = DB_NAME
        self.ai_patterns = {
            'openai': {
                'domains': [r'api\.openai\.com'],
                'pattern': r'(api\.openai\.com)', # Pattern for DNS/HTTP Host header
                'api_key_regex': r'(sk-[a-zA-Z0-9]{32,})'
            },
            'anthropic': {
                'domains': [r'api\.anthropic\.com'],
                'pattern': r'(api\.anthropic\.com)',
                'api_key_regex': r'(sk-ant-[a-zA-Z0-9]{32,})'
            },
            'google': {
                'domains': [r'generativelanguage\.googleapis\.com', r'aiplatform\.googleapis\.com'],
                'pattern': r'(generativelanguage\.googleapis\.com|aiplatform\.googleapis\.com)',
                'api_key_regex': r'(AIza[0-9A-Za-z-_]{35})' # Example for Google API Key
            },
            'cohere': {
                'domains': [r'api\.cohere\.ai'],
                'pattern': r'(api\.cohere\.ai)',
                'api_key_regex': r'([a-zA-Z0-9]{40})' # Placeholder, need actual pattern
            }
            # Add more AI providers as needed
        }
        self.detected_ai = [] # Temporary list for detections before saving to DB
        self.stop_sniffing = threading.Event()

        self.initialize_database()

    def initialize_database(self):
        conn = sqlite3.connect(self.db_name)
        cursor = conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS detected_ai_systems (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT,
                source_ip TEXT,
                destination_ip TEXT,
                destination_port INTEGER,
                protocol TEXT,
                domain TEXT,
                ai_provider TEXT,
                api_key_found BOOLEAN,
                method TEXT,
                confidence REAL
            )
        ''')
        conn.commit()
        conn.close()

    def _save_result(self, data):
        conn = sqlite3.connect(self.db_name)
        cursor = conn.cursor()
        cursor.execute("INSERT INTO detected_ai_systems (timestamp, source_ip, destination_ip, destination_port, protocol, domain, ai_provider, api_key_found, method, confidence) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                       (data['timestamp'], data['source_ip'], data['destination_ip'], data['destination_port'], data['protocol'], data['domain'], data['ai_provider'], data['api_key_found'], data['method'], data['confidence']))
        conn.commit()
        conn.close()
        # print(f"[DB] Saved detection for {data.get('ai_provider', 'Unknown')} from {data.get('source_ip', 'Unknown')}")

    def analyze_packet(self, packet):
        """
        Examines each network packet for AI signatures.
        """
        if self.stop_sniffing.is_set():
            return # Stop processing if event is set

        src_ip = None
        dst_ip = None
        protocol = 'UNKNOWN'
        dst_port = None
        domain = None
        detected_provider = None
        api_key_found = False
        method = 'UNKNOWN'
        confidence = 0.0
        payload_str = ''

        if packet.haslayer(IP):
            src_ip = packet[IP].src
            dst_ip = packet[IP].dst
            protocol = 'TCP' if packet.haslayer(TCP) else ('UDP' if packet.haslayer(UDP) else str(packet[IP].proto))

            if packet.haslayer(TCP):
                dst_port = packet[TCP].dport
            elif packet.haslayer(UDP):
                dst_port = packet[UDP].dport

            # Check for DNS queries to AI domains
            if packet.haslayer(DNS) and packet[DNS].qr == 0:  # DNS Query
                if hasattr(packet[DNS].qd, 'qname'): # Ensure qname exists
                    qname = packet[DNS].qd.qname.decode('utf-8').rstrip('.')
                    for provider, config in self.ai_patterns.items():
                        for dom_pattern in config['domains']:
                            if re.search(dom_pattern, qname):
                                detected_provider = provider
                                domain = qname
                                method = 'DNS_QUERY'
                                confidence = 0.9
                                # print(f"  ✓ Detected {provider} DNS query to {qname}")
                                break
                        if detected_provider: break

            # Check for HTTP/HTTPS traffic (looking for Host header or raw payload)
            if packet.haslayer(Raw):
                try:
                    payload_str = packet[Raw].load.decode('utf-8', errors='ignore')
                    method = 'HTTP_REQUEST'
                    confidence = 0.95
                except UnicodeDecodeError:
                    pass

                # Look for API keys in the raw payload
                for provider, config in self.ai_patterns.items():
                    if config.get('api_key_regex'):
                        matches = re.findall(config['api_key_regex'], payload_str)
                        if matches:
                            api_key_found = True
                            detected_provider = provider # Assign provider if API key found
                            domain = domain or dst_ip # Default to destination IP if no domain from DNS
                            # print(f"  ⚠ API Key detected for {provider} from {src_ip}: {matches[0][:8]}...")
                            break

                # Look for domain patterns in payload (e.g., Host header)
                if not detected_provider:
                    for provider, config in self.ai_patterns.items():
                        for dom_pattern in config['domains']:
                            if re.search(dom_pattern, payload_str):
                                detected_provider = provider
                                domain = domain or dom_pattern.replace('\\.', '.') # Get actual domain from regex
                                # print(f"  ✓ Detected {provider} HTTP traffic from {src_ip}")
                                break
                        if detected_provider: break

        if detected_provider:
            detection_data = {
                'timestamp': datetime.datetime.now().isoformat(),
                'source_ip': src_ip,
                'destination_ip': dst_ip,
                'destination_port': dst_port,
                'protocol': protocol,
                'domain': domain,
                'ai_provider': detected_provider,
                'api_key_found': api_key_found,
                'method': method,
                'confidence': confidence
            }
            self._save_result(detection_data)

    def start_capture(self, interface='eth0', count=0, timeout=None):
        """
        Begins live network monitoring. Uses a threading.Event to stop sniffing.
        """
        self.stop_sniffing.clear()
        print(f"Starting packet capture on interface {interface}...")
        print("Press Ctrl+C to stop.")

        def _sniff_thread():
            sniff(iface=interface, prn=self.analyze_packet, store=0, count=count, timeout=timeout,
                  stop_filter=lambda p: self.stop_sniffing.is_set())
            print("Sniffing thread finished.")

        self.sniff_thread = threading.Thread(target=_sniff_thread)
        self.sniff_thread.start()

        if timeout is not None:
            # Wait for the sniff_thread to finish, or for timeout if it's set
            self.sniff_thread.join(timeout=timeout)
            if self.sniff_thread.is_alive():
                print(f"Capture timed out after {timeout} seconds.")
                self.stop_sniffing.set() # Signal thread to stop
                self.sniff_thread.join() # Wait for thread to terminate

    def stop_capture(self):
        """
        Stops the ongoing packet capture.
        """
        if self.sniff_thread and self.sniff_thread.is_alive():
            print("Stopping packet capture...")
            self.stop_sniffing.set() # Signal the sniff thread to stop
            self.sniff_thread.join() # Wait for the thread to actually stop
            print("Packet capture stopped.")
        else:
            print("No active capture to stop.")

    def process_pcap_file(self, pcap_file_path):
        """
        Reads packets from a .pcap file and processes them using analyze_packet.
        """
        print(f"Processing pcap file: {pcap_file_path}...")
        try:
            packets = rdpcap(pcap_file_path)
            for i, packet in enumerate(packets):
                # Simulate live capture for stop event compatibility (though not strictly necessary for offline)
                if self.stop_sniffing.is_set():
                    print("Pcap processing stopped by signal.")
                    break
                self.analyze_packet(packet)
            print(f"Finished processing {len(packets)} packets from {pcap_file_path}.")
        except FileNotFoundError:
            print(f"Error: Pcap file not found at {pcap_file_path}")
        except Exception as e:
            print(f"An error occurred during pcap processing: {e}")

    def get_shadow_ai_summary(self):
        """
        Returns statistics on detected AI usage.
        """
        conn = sqlite3.connect(self.db_name)
        cursor = conn.cursor()
        summary = {}

        cursor.execute("SELECT COUNT(*) FROM detected_ai_systems")
        summary['total_detections'] = cursor.fetchone()[0]

        cursor.execute("SELECT DISTINCT ai_provider FROM detected_ai_systems")
        summary['detected_providers'] = [row[0] for row in cursor.fetchall()]

        cursor.execute("SELECT ai_provider, COUNT(*) FROM detected_ai_systems GROUP BY ai_provider")
        summary['detections_by_provider'] = cursor.fetchall()

        cursor.execute("SELECT source_ip, COUNT(*) FROM detected_ai_systems GROUP BY source_ip ORDER BY COUNT(*) DESC LIMIT 5")
        summary['top_source_ips'] = cursor.fetchall()

        cursor.execute("SELECT COUNT(DISTINCT source_ip) FROM detected_ai_systems")
        summary['unique_source_ips'] = cursor.fetchone()[0]

        conn.close()
        return summary

    def get_detected_systems(self):
        """
        Returns all detected AI systems from the database.
        """
        conn = sqlite3.connect(self.db_name)
        cursor = conn.cursor()
        cursor.execute("SELECT id, ai_provider, domain, source_ip, timestamp, method, confidence, api_key_found FROM detected_ai_systems ORDER BY timestamp DESC")
        results = cursor.fetchall()
        conn.close()
        return results

if __name__ == '__main__':
    print("Discovery Engine module loaded. Create an instance of DiscoveryEngine to use it.")
    # Example usage:
    # engine = DiscoveryEngine()
    # engine.start_capture(interface='eth0', timeout=60)
    # summary = engine.get_shadow_ai_summary()
    # print(summary)

"""### Test Script: Simulating AI Network Traffic

This script will simulate HTTP requests to the domains of various AI providers. While these requests might not succeed (due to authentication, rate limiting, or being run from a Colab environment), they will generate network traffic (DNS lookups, TCP connections, HTTP host headers) that your `discovery_engine.py` can observe. We'll also simulate the presence of API keys in a dummy request body to test the regex detection.
"""

# simulate_ai_traffic.py

import requests
import time
import random

# Re-using the AI_API_PATTERNS from discovery_engine.py for consistency
AI_API_PATTERNS = {
    'openai': {
        'domains': [r'api\.openai\.com'],
        'api_key_regex': r'sk-[a-zA-Z0-9]{32,}'
    },
    'anthropic': {
        'domains': [r'api\.anthropic\.com'],
        'api_key_regex': r'sk-ant-[a-zA-Z0-9]{32,}'
    },
    'google': {
        'domains': [r'generativelanguage\.googleapis\.com', r'aiplatform\.googleapis\.com'],
        'api_key_regex': None # Google API keys often sent differently or through OAuth
    }
}

def simulate_traffic(num_requests=5):
    print("Starting traffic simulation...")
    for i in range(num_requests):
        provider = random.choice(list(AI_API_PATTERNS.keys()))
        domains = AI_API_PATTERNS[provider]['domains']
        target_domain = random.choice(domains).replace('\\.', '.') # Convert regex to actual domain

        # Construct a dummy URL, usually HTTPS
        url = f"https://{target_domain}/v1/chat/completions" # Example endpoint

        headers = {'Content-Type': 'application/json'}
        body = {"model": "gpt-4", "messages": [{"role": "user", "content": "Hello"}]}

        # Simulate API key in a header or body (for regex detection testing)
        if AI_API_PATTERNS[provider]['api_key_regex']:
            dummy_api_key = "sk-fake" + ''.join(random.choices('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=40))
            # We'll put it in a dummy body string for this simulation
            # In a real scenario, it would be in headers like 'Authorization': f'Bearer {dummy_api_key}'
            body['api_key_candidate'] = dummy_api_key
            print(f"  Simulating traffic to {provider} ({url}) with a dummy API key: {dummy_api_key[:10]}...")
        else:
            print(f"  Simulating traffic to {provider} ({url})...")

        try:
            # Use a short timeout as these requests are unlikely to succeed
            response = requests.post(url, headers=headers, json=body, timeout=2)
            # print(f"    Request to {url} returned status {response.status_code}")
        except requests.exceptions.RequestException as e:
            # print(f"    Request to {url} failed: {e}")
            pass # Expected failures for non-existent/unauthorized endpoints
        finally:
            # Small delay between requests
            time.sleep(random.uniform(0.5, 1.5))

    print("Traffic simulation finished.")

# To run the simulation, uncomment the line below:
simulate_traffic(num_requests=10)

# Note: To observe this traffic with discovery_engine.py, you would typically run discovery_engine.py
# in a separate terminal and then execute this simulation script. Colab's environment might make
# direct `sniff` from discovery_engine.py difficult to capture traffic from the same Colab instance.
# For proper validation, you might need to run the sniffing on a gateway or another machine.

"""### `api.py`: FastAPI Server Implementation

This file sets up a FastAPI server to expose the `DiscoveryEngine`'s functionalities and data. It will include endpoints for server status, detected systems, summary statistics, triggering scans, and checking scan status.
"""

# api.py

!pip install fastapi uvicorn pydantic # Install required libraries

from fastapi import FastAPI, HTTPException, BackgroundTasks
from pydantic import BaseModel
from typing import Optional, List
import json
import threading

# Import the DiscoveryEngine class from the discovery_engine.py cell
# In a real project, this would be `from discovery_engine import DiscoveryEngine`
# For Colab, we'll execute the cell containing the class definition.

# NOTE: For Colab, ensure the discovery_engine.py cell is run first.
# We will manually create an instance here after ensuring it's available.

# Placeholder for DiscoveryEngine if running this cell independently for testing
# In a connected Colab environment, the class should already be defined from cell 19c8ec6d
try:
    from discovery_engine import DiscoveryEngine
except ImportError:
    # This block handles cases where discovery_engine.py isn't a separate file
    # and the class needs to be defined or imported from a different scope.
    # In a typical Colab flow, the previous cell would have defined it.
    # For robustness, we might re-execute the class definition or assume it exists.
    pass # Assuming DiscoveryEngine is already defined in the notebook's global scope


app = FastAPI(
    title="Sovryn AI Discovery Engine API",
    description="Detects Shadow AI on your network",
    version="1.0.0"
)

# Initialize the engine
engine = DiscoveryEngine()

# Background capture thread status
is_capturing = False

class ScanRequest(BaseModel):
    interface: str = "lo" # Default to 'lo' for loopback in Colab environment
    count: int = 100
    timeout: int = 30

class SystemResponse(BaseModel):
    id: int
    provider: str
    destination: str
    source_ip: str
    timestamp: str
    method: str
    confidence: float
    api_key_found: Optional[bool] = False

@app.get("/")
def read_root():
    return {
        "message": "Sovryn AI Discovery Engine",
        "status": "running",
        "version": "1.0.0"
    }

@app.get("/systems", response_model=List[SystemResponse])
def get_systems():
    """Get all detected systems"""
    results = engine.get_detected_systems()
    return [
        {
            "id": r[0],
            "provider": r[1],
            "destination": r[2],
            "source_ip": r[3],
            "timestamp": r[4],
            "method": r[5],
            "confidence": r[6],
            "api_key_found": r[7] # Ensure this matches DB schema
        }
        for r in results
    ]

@app.get("/shadow-ai-summary")
def get_shadow_ai_summary():
    """Get Shadow AI summary statistics"""
    return engine.get_shadow_ai_summary()

@app.post("/scan")
async def trigger_scan(request: ScanRequest, background_tasks: BackgroundTasks):
    """Trigger a manual network scan"""
    global is_capturing

    if is_capturing:
        raise HTTPException(status_code=409, detail="A scan is already in progress")

    def run_scan_blocking():
        global is_capturing
        is_capturing = True
        try:
            # Ensure the database is initialized before starting capture
            engine.initialize_database()
            engine.start_capture(
                interface=request.interface,
                count=request.count,
                timeout=request.timeout
            )
        except Exception as e:
            print(f"Scan error: {e}")
        finally:
            is_capturing = False

    background_tasks.add_task(run_scan_blocking)
    return {"message": "Scan started", "interface": request.interface, "count": request.count, "timeout": request.timeout}

@app.get("/scan-status")
def get_scan_status():
    """Check if a scan is currently running"""
    return {"is_capturing": is_capturing}

@app.delete("/systems")
def clear_systems():
    """Clear all detected systems (for testing)"""
    try:
        import sqlite3
        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()
        cursor.execute("DELETE FROM detected_ai_systems") # Correct table name
        conn.commit()
        conn.close()
        return {"message": "All systems cleared"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# To run the FastAPI app, you would typically use:
# import uvicorn
# if __name__ == "__main__":
#    uvicorn.run(app, host="0.0.0.0", port=8000)

"""### Run the FastAPI Server

This cell will start the FastAPI application using Uvicorn. It will run indefinitely until stopped. While running, you can interact with the API from other cells or via an external tool if exposed (e.g., with `ngrok`).

**To stop the server:** Click the stop button on the left of this cell's output, or interrupt the kernel.
"""

!pip install nest_asyncio
import uvicorn
import threading
import time
import nest_asyncio

# Apply nest_asyncio to allow nested event loops
nest_asyncio.apply()

# This will run the FastAPI app in a separate thread.
# The port 8000 is used by default in the examples.
# You can access the API at http://127.0.0.1:8000 from within the Colab environment.

print("Starting FastAPI server on http://0.0.0.0:8000 in a background thread using nest_asyncio...")

def run_uvicorn():
    uvicorn.run(app, host="0.0.0.0", port=8000)

uvicorn_thread = threading.Thread(target=run_uvicorn)
uvicorn_thread.start()

# Give the server a moment to start up
time.sleep(5)
print("FastAPI server started. You can now execute the API test cells.")
print("To stop the server, you will need to interrupt the kernel or restart the runtime.")

"""### Test the API Endpoints

Since the FastAPI server is running locally within the Colab environment, we can use `httpx` to make requests to it. First, let's install `httpx`.
"""

!pip install httpx

import httpx

BASE_URL = "http://127.0.0.1:8000"

# Test Root Endpoint
print("\n--- Testing / (root) ---")
try:
    response = httpx.get(f"{BASE_URL}/")
    response.raise_for_status()
    print(f"Status Code: {response.status_code}")
    print(f"Response: {response.json()}")
except httpx.RequestError as e:
    print(f"Request failed: {e}")
except httpx.HTTPStatusError as e:
    print(f"Error response {e.response.status_code} while requesting {e.request.url}: {e.response.text}")

import httpx

BASE_URL = "http://127.0.0.1:8000"

# Test Shadow AI Summary Endpoint
print("\n--- Testing /shadow-ai-summary ---")
try:
    response = httpx.get(f"{BASE_URL}/shadow-ai-summary")
    response.raise_for_status()
    print(f"Status Code: {response.status_code}")
    print(f"Response: {response.json()}")
except httpx.RequestError as e:
    print(f"Request failed: {e}")
except httpx.HTTPStatusError as e:
    print(f"Error response {e.response.status_code} while requesting {e.request.url}: {e.response.text}")

import httpx

BASE_URL = "http://127.0.0.1:8000"

# Test Get Systems Endpoint
print("\n--- Testing /systems ---")
try:
    response = httpx.get(f"{BASE_URL}/systems")
    response.raise_for_status()
    print(f"Status Code: {response.status_code}")
    print(f"Response (first 3): {response.json()[:3]}")
    print(f"Total systems detected: {len(response.json())}")
except httpx.RequestError as e:
    print(f"Request failed: {e}")
except httpx.HTTPStatusError as e:
    print(f"Error response {e.response.status_code} while requesting {e.request.url}: {e.response.text}")

import httpx
import time

BASE_URL = "http://127.0.0.1:8000"

# Test Trigger Scan Endpoint
print("\n--- Testing /scan (trigger a network scan) ---")
scan_request_payload = {"interface": "lo", "count": 20, "timeout": 10}
try:
    response = httpx.post(f"{BASE_URL}/scan", json=scan_request_payload)
    response.raise_for_status()
    print(f"Status Code: {response.status_code}")
    print(f"Response: {response.json()}")
except httpx.RequestError as e:
    print(f"Request failed: {e}")
except httpx.HTTPStatusError as e:
    print(f"Error response {e.response.status_code} while requesting {e.request.url}: {e.response.text}")

# Give some time for the background scan to potentially start
print("Waiting a few seconds for scan to initiate...")
time.sleep(2)

import httpx

BASE_URL = "http://127.0.0.1:8000"

# Test Scan Status Endpoint
print("\n--- Testing /scan-status ---")
try:
    response = httpx.get(f"{BASE_URL}/scan-status")
    response.raise_for_status()
    print(f"Status Code: {response.status_code}")
    print(f"Response: {response.json()}")
except httpx.RequestError as e:
    print(f"Request failed: {e}")
except httpx.HTTPStatusError as e:
    print(f"Error response {e.response.status_code} while requesting {e.request.url}: {e.response.text}")

import httpx

BASE_URL = "http://127.0.0.1:8000"

# Test Get Systems Endpoint AGAIN after a scan to see if new data appeared
print("\n--- Testing /systems (after scan) ---")
try:
    response = httpx.get(f"{BASE_URL}/systems")
    response.raise_for_status()
    print(f"Status Code: {response.status_code}")
    print(f"Response (first 3): {response.json()[:3]}")
    print(f"Total systems detected: {len(response.json())}")
except httpx.RequestError as e:
    print(f"Request failed: {e}")
except httpx.HTTPStatusError as e:
    print(f"Error response {e.response.status_code} while requesting {e.request.url}: {e.response.text}")

import httpx

BASE_URL = "http://127.0.0.1:8000"

# Test Clear Systems Endpoint
print("\n--- Testing /systems (DELETE to clear) ---")
try:
    response = httpx.delete(f"{BASE_URL}/systems")
    response.raise_for_status()
    print(f"Status Code: {response.status_code}")
    print(f"Response: {response.json()}")
except httpx.RequestError as e:
    print(f"Request failed: {e}")
except httpx.HTTPStatusError as e:
    print(f"Error response {e.response.status_code} while requesting {e.request.url}: {e.response.text}")

"""### Verify Database Contents Directly

To confirm that the `discovery.db` SQLite database is being updated correctly, we can query it directly using `sqlite3`.
"""

import sqlite3

DB_NAME = 'discovery.db'

print(f"\n--- Querying {DB_NAME} directly ---")
try:
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM detected_ai_systems ORDER BY timestamp DESC LIMIT 5")
    results = cursor.fetchall()

    if results:
        print("Latest 5 entries in detected_ai_systems:")
        # Print column names
        column_names = [description[0] for description in cursor.description]
        print(column_names)
        for row in results:
            print(row)
    else:
        print("No entries found in detected_ai_systems table.")

    # Get count of all entries
    cursor.execute("SELECT COUNT(*) FROM detected_ai_systems")
    count = cursor.fetchone()[0]
    print(f"Total entries in detected_ai_systems: {count}")

    conn.close()
except sqlite3.Error as e:
    print(f"Database error: {e}")

"""# Task
The user is working on a project to detect 'Shadow AI' usage on a network. They have developed a `DiscoveryEngine` in `discovery_engine.py` that uses `scapy` to sniff network packets and identify AI API calls, saving detections to a SQLite database. They also have a FastAPI application in `api.py` to expose the engine's functionalities. A `simulate_ai_traffic.py` script was provided to generate dummy AI traffic.

The current problem is that the FastAPI server starts but all API calls result in 'Connection refused' errors. Additionally, direct querying of the `discovery.db` shows no detected systems, even after simulating traffic. This indicates that the `scapy.sniff` function within the Colab environment is likely not capturing the self-generated traffic, and thus no data is being saved to the database.

The task is to address the issue of network traffic capture in Colab. Since direct live sniffing of loopback traffic in Colab is problematic, the plan involves simulating the detection process by either directly populating the database or, more robustly, processing a pre-recorded `pcap` file. This will allow the user to test the `DiscoveryEngine`'s detection capabilities and the FastAPI API's ability to retrieve these detections, despite the Colab environment's limitations for live sniffing.

Here's a breakdown of the steps:

1.  **Explain Colab Network Capture Limitations**: Provide a detailed explanation of why `scapy.sniff` might not capture loopback or self-generated traffic effectively within a Colab container, clarifying the environment's sandboxed nature.
2.  **Prepare Sample Pcap File (or alternative)**: Since direct `pcap` generation for self-generated traffic within Colab is complex, I will explain how to obtain or create a `pcap` file with simulated AI traffic. For immediate testing, I will provide a method to directly populate the database with 'simulated detections' as if they were captured, or use a sample pcap if available to demonstrate the `analyze_packet` functionality.
3.  **Modify DiscoveryEngine for Pcap Analysis**: Update the `DiscoveryEngine` class to include a new method that can read and process packets from a `pcap` file using `rdpcap` (read pcap) from Scapy, feeding them to the existing `analyze_packet` logic. This will allow offline testing of the detection capabilities.
4.  **Execute Pcap Analysis**: Run the modified `DiscoveryEngine`'s new method to process the prepared `pcap` file or simulated data, ensuring that the `analyze_packet` function is called for each packet and detected AI activity is saved to the database.
5.  **Verify Database Contents After Pcap Analysis**: Query the `discovery.db` database directly using `sqlite3` to confirm that new entries for detected AI systems have been successfully added after processing the `pcap` file or simulated data, including summary statistics.
6.  **Finish task**: Provide a summary of the successful offline detection and discuss further steps, such as strategies for live traffic capture in Colab or alternative deployment considerations.

## Explain Colab Network Capture Limitations

### Subtask:
Provide a detailed explanation of why `scapy.sniff` might not capture loopback or self-generated traffic effectively within a Colab container.

```markdown
### Colab Network Capture Limitations

Google Colab provides a sandboxed environment, typically a Docker container, where your code executes. This isolation, while beneficial for security and resource management, introduces several challenges for direct network sniffing, especially for loopback or self-generated traffic:

1.  **Network Namespace Isolation**: Each Colab instance runs in its own network namespace. This means that processes within one container generally cannot directly observe the network traffic of other containers or the host system without specific configurations or privileges that are usually not available in a standard Colab setup.

2.  **Loopback Interface (`lo`)**: While a loopback interface (`lo`) exists within the container, `scapy.sniff` often struggles to capture traffic generated by other processes *within the same container* on this interface, particularly if the traffic doesn't traverse a physical network interface. The `simulate_ai_traffic.py` script generates traffic from within the same container, and `scapy.sniff` might not be configured or have the necessary permissions to intercept this internal loopback communication effectively.

3.  **Privilege Requirements**: Network sniffing tools like Scapy often require elevated privileges (e.g., `CAP_NET_RAW`, `CAP_NET_ADMIN`). In a shared cloud environment like Colab, these privileges are typically restricted for security reasons, preventing direct access to raw network sockets or interfaces in a promiscuous mode.

4.  **Virtual Network Devices**: Colab's network setup might involve various virtual network devices (e.g., `eth0`) that bridge to Google's internal infrastructure. While `scapy.sniff` *might* capture external traffic reaching or leaving the container via `eth0`, capturing internal container-to-container or internal process-to-process communication is far more complex and often impossible without direct access to the host's networking stack.

**Conclusion**: Due to these limitations, directly using `scapy.sniff` within a Colab notebook to capture and analyze network traffic generated by another script running *in the same Colab instance* (especially loopback traffic or traffic that doesn't leave the container) is generally unreliable and often fails. This is why the `discovery.db` currently shows no detections, even after simulating traffic.

To overcome this for the purpose of testing the `DiscoveryEngine`'s logic, we will shift to an offline analysis approach using pre-recorded `pcap` files or direct database population.

## Prepare Sample Pcap File (or alternative)

### Subtask:
Explain how to obtain or create a `pcap` file with simulated AI traffic. For immediate testing, provide a method to directly populate the database with 'simulated detections' as if they were captured, or use a sample pcap if available to demonstrate the `analyze_packet` functionality.

```markdown
### Challenges in Generating a Pcap File in Colab and Solutions

Generating a `.pcap` (packet capture) file for self-generated network traffic directly within the Colab environment poses significant challenges, similar to those encountered with live sniffing:

1.  **Limited Sniffing Capabilities**: As previously discussed, `scapy.sniff` struggles to capture loopback or internal container traffic. This means that even if you try to run `scapy` to write packets to a `pcap` file, it might not capture the traffic generated by `simulate_ai_traffic.py` effectively.
2.  **Privilege Restrictions**: Writing raw network packets often requires elevated privileges, which are restricted in Colab for security reasons.

Given these limitations, there are two primary approaches to obtain data for offline analysis of the `DiscoveryEngine`'s detection logic:

1.  **Use a Pre-recorded Pcap File**: The most robust solution is to obtain a `.pcap` file that contains legitimate AI API traffic recorded from a controlled environment (e.g., a local machine where you can perform live sniffing). This file can then be uploaded to Colab for processing. For this task, we will consider using a sample `pcap` if one becomes available, or generate a placeholder one if necessary to demonstrate the `rdpcap` functionality.

2.  **Directly Populate the Database**: For immediate testing and to verify the `DiscoveryEngine`'s ability to store and retrieve detected systems via the FastAPI, we can bypass the sniffing mechanism entirely and directly insert simulated detection records into the `discovery.db` SQLite database. This allows us to quickly test the API and the summary functions without the complexities of network capture in Colab.

For the next step, we will proceed with **directly populating the database** with simulated detections to unblock the API testing and then explore `pcap` processing.
```

**Reasoning**:
I need to insert simulated AI detection data directly into the `detected_ai_systems` table in `discovery.db` to bypass the network sniffing limitations and enable testing of the `DiscoveryEngine` and FastAPI.
"""

import sqlite3
import datetime
import random

DB_NAME = 'discovery.db'

def populate_database_with_simulated_detections(num_entries=5):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()

    # Clear existing data for a clean test
    cursor.execute("DELETE FROM detected_ai_systems")
    conn.commit()
    print("Cleared existing entries from detected_ai_systems table.")

    ai_providers = ['openai', 'anthropic', 'google', 'cohere']
    domains = {
        'openai': ['api.openai.com'],
        'anthropic': ['api.anthropic.com'],
        'google': ['generativelanguage.googleapis.com', 'aiplatform.googleapis.com'],
        'cohere': ['api.cohere.ai']
    }
    methods = ['DNS_QUERY', 'HTTP_REQUEST', 'API_KEY_DETECTED']

    for _ in range(num_entries):
        provider = random.choice(ai_providers)
        domain = random.choice(domains[provider])
        source_ip = f"192.168.1.{random.randint(10, 250)}"
        dest_ip = f"104.20.{random.randint(0, 255)}.{random.randint(0, 255)}"
        dest_port = random.choice([80, 443, 8000])
        protocol = 'TCP'
        timestamp = (datetime.datetime.now() - datetime.timedelta(minutes=random.randint(1, 60))).isoformat()
        method = random.choice(methods)
        api_key_found = random.choice([True, False])
        confidence = round(random.uniform(0.7, 0.99), 2)

        cursor.execute(
            "INSERT INTO detected_ai_systems (timestamp, source_ip, destination_ip, destination_port, protocol, domain, ai_provider, api_key_found, method, confidence) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (timestamp, source_ip, dest_ip, dest_port, protocol, domain, provider, api_key_found, method, confidence)
        )
    conn.commit()
    conn.close()
    print(f"Inserted {num_entries} simulated AI detection entries.")

# Call the function to populate the database
populate_database_with_simulated_detections(num_entries=10)

# Verify the database contents
print(f"\n--- Querying {DB_NAME} directly after population ---")
try:
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM detected_ai_systems ORDER BY timestamp DESC LIMIT 5")
    results = cursor.fetchall()

    if results:
        print("Latest 5 entries in detected_ai_systems:")
        column_names = [description[0] for description in cursor.description]
        print(column_names)
        for row in results:
            print(row)
    else:
        print("No entries found in detected_ai_systems table after population.")

    cursor.execute("SELECT COUNT(*) FROM detected_ai_systems")
    count = cursor.fetchone()[0]
    print(f"Total entries in detected_ai_systems: {count}")

    conn.close()
except sqlite3.Error as e:
    print(f"Database error: {e}")

"""## Modify DiscoveryEngine for Pcap Analysis

### Subtask:
Update the `DiscoveryEngine` class to include a new method that can read and process packets from a `pcap` file using `rdpcap` (read pcap) from Scapy, feeding them to the existing `analyze_packet` logic. This will allow offline testing of the detection capabilities.

## Execute Pcap Analysis

### Subtask:
Run the modified `DiscoveryEngine`'s new method to process the prepared `pcap` file or simulated data, ensuring that the `analyze_packet` function is called for each packet and detected AI activity is saved to the database.

**Reasoning**:
First, I need to re-instantiate the DiscoveryEngine to ensure the updated class definition (with the `process_pcap_file` method) is used. Then, I will create a dummy pcap file and call the `process_pcap_file` method, followed by getting the summary of detected AI systems from the database.
"""

from scapy.all import wrpcap, Packet

# Re-instantiate the DiscoveryEngine to ensure the latest class definition is used
engine = DiscoveryEngine()
print("DiscoveryEngine re-instantiated with updated methods.")

# 2. Create a dummy (empty) .pcap file
dummy_pcap_file = "dummy_traffic.pcap"
wrpcap(dummy_pcap_file, []) # Create an empty pcap file
print(f"Created a dummy pcap file: {dummy_pcap_file}")

# 3. Call the process_pcap_file method with the dummy pcap
engine.process_pcap_file(dummy_pcap_file)

# 4. Retrieve and print the shadow AI summary from the database
# This will reflect the data populated in the previous step.
print("\n--- Shadow AI Summary from Database (after dummy pcap processing) ---")
summary = engine.get_shadow_ai_summary()
for key, value in summary.items():
    print(f"{key}: {value}")

import os
if os.path.exists(dummy_pcap_file):
    os.remove(dummy_pcap_file)
    print(f"Removed dummy pcap file: {dummy_pcap_file}")

"""**Reasoning**:
I need to clear the database first to ensure that the detection results solely come from the pcap processing. Then I will generate a pcap file with simulated AI traffic using Scapy, process it with the DiscoveryEngine, and verify that the detections are correctly added to the database.


"""

from scapy.all import IP, TCP, UDP, DNS, DNSQR, Raw, wrpcap, Packet
import sqlite3
import datetime
import random

# Re-instantiate the DiscoveryEngine to ensure the latest class definition is used
engine = DiscoveryEngine()
print("DiscoveryEngine re-instantiated with updated methods.")

# Clear existing data for a clean test of pcap processing
conn = sqlite3.connect(DB_NAME)
cursor = conn.cursor()
cursor.execute("DELETE FROM detected_ai_systems")
conn.commit()
conn.close()
print("Cleared existing entries from detected_ai_systems table for pcap test.")

# 1. Create a dummy .pcap file with simulated AI traffic
dummy_pcap_file = "simulated_ai_traffic.pcap"

packets_to_write = []

# Simulate an OpenAI DNS query
packets_to_write.append(
    IP(dst="8.8.8.8")/UDP(dport=53)/DNS(rd=1, qd=DNSQR(qname="api.openai.com"))
)

# Simulate an Anthropic HTTP request (basic, just Host header in Raw layer)
http_request = b"GET /v1/messages HTTP/1.1\r\nHost: api.anthropic.com\r\nUser-Agent: test-client\r\nAccept: */*\r\n\r\n"
packets_to_write.append(
    IP(src="192.168.1.10", dst="104.20.0.10")/TCP(dport=443, sport=12345, flags="S") / Raw(load=http_request)
)

# Simulate a Google API key presence in payload
google_payload = b"POST /v1beta/models/gemini:generateContent HTTP/1.1\r\nHost: generativelanguage.googleapis.com\r\nContent-Type: application/json\r\nAuthorization: Bearer AIza_fake_google_api_key_1234567890abcdefghijklmnopqrstuvwxyz\r\n\r\n{"prompt":"hello"}"
packets_to_write.append(
    IP(src="192.168.1.20", dst="142.250.0.20")/TCP(dport=443, sport=54321, flags="S") / Raw(load=google_payload)
)

wrpcap(dummy_pcap_file, packets_to_write) # Create pcap file with packets
print(f"Created a dummy pcap file with {len(packets_to_write)} simulated packets: {dummy_pcap_file}")

# 2. Call the process_pcap_file method with the dummy pcap
engine.process_pcap_file(dummy_pcap_file)

# 3. Retrieve and print the shadow AI summary from the database
print("\n--- Shadow AI Summary from Database (after pcap processing) ---")
summary = engine.get_shadow_ai_summary()
for key, value in summary.items():
    print(f"{key}: {value}")

import os
if os.path.exists(dummy_pcap_file):
    os.remove(dummy_pcap_file)
    print(f"Removed dummy pcap file: {dummy_pcap_file}")

"""**Reasoning**:
The previous code failed due to a `SyntaxError` in the `google_payload` string. The double quotes within the JSON part of the payload need to be escaped to be correctly interpreted as part of the string. I will modify the `google_payload` definition to escape these inner quotes.


"""

from scapy.all import IP, TCP, UDP, DNS, DNSQR, Raw, wrpcap, Packet
import sqlite3
import datetime
import random

# Re-instantiate the DiscoveryEngine to ensure the latest class definition is used
engine = DiscoveryEngine()
print("DiscoveryEngine re-instantiated with updated methods.")

# Clear existing data for a clean test of pcap processing
conn = sqlite3.connect(DB_NAME)
cursor = conn.cursor()
cursor.execute("DELETE FROM detected_ai_systems")
conn.commit()
conn.close()
print("Cleared existing entries from detected_ai_systems table for pcap test.")

# 1. Create a dummy .pcap file with simulated AI traffic
dummy_pcap_file = "simulated_ai_traffic.pcap"

packets_to_write = []

# Simulate an OpenAI DNS query
packets_to_write.append(
    IP(dst="8.8.8.8")/UDP(dport=53)/DNS(rd=1, qd=DNSQR(qname="api.openai.com"))
)

# Simulate an Anthropic HTTP request (basic, just Host header in Raw layer)
http_request = b"GET /v1/messages HTTP/1.1\r\nHost: api.anthropic.com\r\nUser-Agent: test-client\r\nAccept: */*\r\n\r\n"
packets_to_write.append(
    IP(src="192.168.1.10", dst="104.20.0.10")/TCP(dport=443, sport=12345, flags="S") / Raw(load=http_request)
)

# Simulate a Google API key presence in payload
google_payload = b"POST /v1beta/models/gemini:generateContent HTTP/1.1\r\nHost: generativelanguage.googleapis.com\r\nContent-Type: application/json\r\nAuthorization: Bearer AIza_fake_google_api_key_1234567890abcdefghijklmnopqrstuvwxyz\r\n\r\n{\"prompt\":\"hello\"}"
packets_to_write.append(
    IP(src="192.168.1.20", dst="142.250.0.20")/TCP(dport=443, sport=54321, flags="S") / Raw(load=google_payload)
)

wrpcap(dummy_pcap_file, packets_to_write) # Create pcap file with packets
print(f"Created a dummy pcap file with {len(packets_to_write)} simulated packets: {dummy_pcap_file}")

# 2. Call the process_pcap_file method with the dummy pcap
engine.process_pcap_file(dummy_pcap_file)

# 3. Retrieve and print the shadow AI summary from the database
print("\n--- Shadow AI Summary from Database (after pcap processing) ---")
summary = engine.get_shadow_ai_summary()
for key, value in summary.items():
    print(f"{key}: {value}")

import os
if os.path.exists(dummy_pcap_file):
    os.remove(dummy_pcap_file)
    print(f"Removed dummy pcap file: {dummy_pcap_file}")

"""**Reasoning**:
To verify the database contents after processing the simulated pcap file, I will query the `discovery.db` directly using `sqlite3` to display the newly added entries and a summary count.


"""

import sqlite3

DB_NAME = 'discovery.db'

print(f"\n--- Querying {DB_NAME} directly after pcap analysis ---")
try:
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM detected_ai_systems ORDER BY timestamp DESC LIMIT 5")
    results = cursor.fetchall()

    if results:
        print("Latest 5 entries in detected_ai_systems:")
        # Print column names
        column_names = [description[0] for description in cursor.description]
        print(column_names)
        for row in results:
            print(row)
    else:
        print("No entries found in detected_ai_systems table after pcap analysis.")

    # Get count of all entries
    cursor.execute("SELECT COUNT(*) FROM detected_ai_systems")
    count = cursor.fetchone()[0]
    print(f"Total entries in detected_ai_systems: {count}")

    conn.close()
except sqlite3.Error as e:
    print(f"Database error: {e}")

"""## Verify Database Contents After Pcap Analysis

### Subtask:
Query the `discovery.db` database directly using `sqlite3` to confirm that new entries for detected AI systems have been successfully added after processing the `pcap` file, including summary statistics.

"""